// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAj_6hf1ZfZRvukMwoQPqAfYGOEfk9sGEk',
    appId: '1:857126188561:web:047cecd0a89b1877f8a3b0',
    messagingSenderId: '857126188561',
    projectId: 'flutter-test-aabc7',
    authDomain: 'flutter-test-aabc7.firebaseapp.com',
    storageBucket: 'flutter-test-aabc7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4PHd6hmmmdQWTPCbugcNdxPP5glQRFY4',
    appId: '1:857126188561:android:e22c80f534482f06f8a3b0',
    messagingSenderId: '857126188561',
    projectId: 'flutter-test-aabc7',
    storageBucket: 'flutter-test-aabc7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGBcCtXMfwGW2EweCmPEZh3q4j00WontQ',
    appId: '1:857126188561:ios:aaeabd571b6d43e0f8a3b0',
    messagingSenderId: '857126188561',
    projectId: 'flutter-test-aabc7',
    storageBucket: 'flutter-test-aabc7.appspot.com',
    iosClientId: '857126188561-ne3es4ar2ktl77tjt90ddk23sbbk1pbi.apps.googleusercontent.com',
    iosBundleId: 'com.codigocorrecto.crud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGBcCtXMfwGW2EweCmPEZh3q4j00WontQ',
    appId: '1:857126188561:ios:aaeabd571b6d43e0f8a3b0',
    messagingSenderId: '857126188561',
    projectId: 'flutter-test-aabc7',
    storageBucket: 'flutter-test-aabc7.appspot.com',
    iosClientId: '857126188561-ne3es4ar2ktl77tjt90ddk23sbbk1pbi.apps.googleusercontent.com',
    iosBundleId: 'com.codigocorrecto.crud',
  );
}
